site_name: Kitchen Road
repo_url: "https://github.com/Kitchen-Road"
edit_uri: ""

theme: 
  name: material
  features: navigation.tabs
  palette:
    primary: red

nav:
  - Início: "index.md"
  - Projeto: 
    - Documento de arquitetura: "projeto/documento_arquitetura.md"