site_name: Kitchen Road
repo_url: "https://github.com/Kitchen-Road"
site_description: Repositório do Kitchen Road
edit_uri: ""

theme:
  name: material
  features: navigation.tabs
  palette:
    primary: red

nav:
  - Início: "index.md"
  - Projeto:
      - Documento de Arquitetura: "projeto/Arquitetura.md"
      - Documento de Visão: "projeto/Documento_de_visao.md"
  - Produto:
      - Backlog: "produto/Product_backlog.md"
      
